name: Build YDB Java SDK

on:
  push:
    branches:
      - master
      - develop
      - release*
  pull_request:
      type: [opened, reopened, edited, synchronize]

jobs:
  build:
    name: Build YDB Java SDK
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '8', '11', '17', '21']

    env:
        MAVEN_ARGS: --batch-mode --update-snapshots -Dstyle.color=always -DYDB_DOCKER_ISOLATION=true

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn $MAVEN_ARGS verify

  coverage:
    if: github.repository == 'ydb-platform/ydb-java-sdk'
    name: Coverage YDB Java SDK
    runs-on: ubuntu-latest
    needs: build

    env:
        MAVEN_ARGS: --batch-mode --update-snapshots -Dstyle.color=always -DYDB_DOCKER_ISOLATION=true

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn $MAVEN_ARGS test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

